# Generated by Django 4.2 on 2025-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('bearer', models.CharField(max_length=255)),
            ],
        ),
    ]
